### ISSUE TITLE
Game will only let you play one card

### ISSUE THREAD

**Issue by mooreka21** [simonk21/Ben#8]
1. start new local game
2. when it is your turn, you aren't allowed to play more than one card in your round. You should be allowed to select multiple and play them.
3. This issue may be causing the smart and dumb AI to be acting similarly 

(based on Nuxoll's notes)

**Comment by mooreka21** [comment]
Nuxoll also mentioned that game should auto-pass when no valid play is available.

**Comment by malikh22** [comment]
issue 1 (game only lets you play one card) - This issue has been resolved. It is now possible to play multiple cards.
issue 2(?) (dumb AI and smart AI acting similarly) - Illegitimate. The dumb AI consistently plays the highest card possible while the smart AI plays the lowest card possible. In addition, when it only has 4 cards left in its hand, the behavior of the smart AI changes based on how many of the highest cards have been played. It is likely that those observing were unaware of the rules/not yet at that point of their games. 
issue 3 (auto-passing): Will not fix. We feel that this is a preference rather than a bug. In an actual card game, passing is always an action, and it is up to each player to consciously pass their turn if they see that they cannot play a card.

**Comment by mooreka21** [comment]
Sounds good!
